name: "dbt_ecommerce_analytics"
version: "1.0.0"
config-version: 2

profile: "dbt_ecommerce_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_ecommerce_analytics:
    +materialized: table

    stg:
      +materialized: table
      +schema: analytics_staging
      +tags: ["staging"]

    int:
      +materialized: incremental
      +schema: analytics_int
      +tags: ["intermediate"]

    final:
      +materialized: view
      +schema: analytics
      +tags: ["final"]

      dimensions:
        +materialized: view
        +tags: ["dimension"]

      facts:
        +materialized: view
        +tags: ["fact"]

      analytcs:
        +materialized: view
        +tags: ["analytics", "reporting"]

seeds:
  dbt_ecommerce_analytics:
    +schema: raw
    +tags: ["seed"]

vars:
  start_date: "2023-01-01"
  key_date: '{{ run_started_at.strftime("%Y-%m-%d") }}'

require-dbt-version: [">=1.0.0"]

flags:
  static_parser: false
  send_anonymous_usage_stats: true
